language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/test_shoes_api

node_js:  
   - "12"

before_script:
  - psql -c 'create database  test_shoes_api;' -U postgres
  - psql -U postgres -d test_shoes_api -a -f table.sql

services:
  - postgresql
